### ISSUE TITLE
Properly Escape Special Characters in Regex for Korean Text Search

### ISSUE THREAD

**Issue by hwahyeon** [hwantage/hansearch#1]
**Issue Summary**:
The `makeRegexByCho` function's current implementation inadequately escapes special characters, affecting searches with symbols like `+`, `*`, `?`. Notably, searches for `"ㅈ렬*"` and `"ㅈ렬"` yield divergent outcomes due to the unescaped `*`.

**Two solutions are proposed**:
```javascript
keyWord.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "");
```
This method involves removing all special characters that could cause issues in regular expressions from the search keywords. However, this approach may disregard the user's intent. For instance, someone might want to use the `*` character as part of their search term.
```javascript
keyWord.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1");
```
This code disables the special functionality that characters have in regular expressions, allowing them to be searched for literally. For example, from an array like ['*이 빛나는 밤', '별이 빛나는 밤'], it would be possible to specifically search for `'*이 빛나는 밤'` using `*`.

Looking forward to your feedback or any further discussion on the proposed solutions.

---
**이슈**:
현재 `makeRegexByCho` 함수에서는 `[()|[\]{}\\]`만을 이스케이프 처리하고 있습니다. 이 때문에 정규 표현식에서 사용될 때 특별한 의미를 가지는 다른 문자들, 예를 들어 `+`, `*`, `?` 문자들이 제대로 이스케이프 되지 않아 오류가 나거나 원치 않는 값이 나오는 것을 확인했습니다. 예를 들어 `hansearch(json, "ㅈ렬*");`과 `hansearch(json, "ㅈ렬");`은 다른 결과를 나타냅니다.
따라서, 정규 표현식에 특별한 의미를 주는 모든 특수 문자를 이스케이프 처리하는 로직으로 개선할 필요가 있다고 생각합니다.

**개선책**:
```javascript
keyWord.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "");
```
검색어에서 정규 표현식에 문제가 될 만한 모든 특수문자를 제거합니다. 하지만 이 방법은 사용자의 의도를 무시할 수 있습니다. 예를 들어, 누군가는 `*` 문자를 검색어로 사용하고 싶을 수 있습니다.

```javascript
keyWord.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1");
```
이 코드는 정규 표현식에서 그 문자가 가진 특별한 기능을 비활성화시켜 문자 그대로를 검색할 수 있게 합니다. 예를 들어, [‘*이 빛나는 밤’, ‘별이 빛나는 밤’]에서 `‘*’`로 `‘*이 빛나는 밤’`을 검색할 수 있습니다.

제안한 개선책에 대한 피드백이나 논의를 기대합니다. 감사합니다!

**Comment by hwantage** [comment]
I tested with the code you suggested and found that the search works perfectly as intended by the user.

I was going to exclude them from the search keyword input and not support searching when special characters are included as it would cause an error in the search behavior, but thank you very much for the great suggestion.

After all the testing for special characters I will be applying this code to the source.

-------------------------------------------------------------------------------------------
제안해 주신 코드로 테스트해 본 결과 사용자가 의도한 대로 검색이 완벽하게 작동하는 것을 확인했습니다.

특수 문자가 포함되면 검색 동작에 오류가 발생할 수 있으므로 검색 키워드 입력에서 제외하여 검색을 지원하지 않으려고 했는데 좋은 제안을 해주셔서 정말 감사합니다.

특수 문자에 대한 모든 테스트가 끝나면 이 코드를 소스에 적용하겠습니다.
